version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user1
      POSTGRES_DB: db_users
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"